### ISSUE TITLE
Insulated mesecons are uncraftable

### ISSUE THREAD

**Issue by qwrwed** [VanessaE/dreambuilder_modpack#12]
In unifiedmesecons/init.lua, several items are unregistered, including "mesecons_insulated:insulated_off". However, their crafting recipes are not unregistered, causing a conflict (the recipe now produces "Unknown Item").

I recommend simply adding aliases for the unregistered items in order to solve the craft conflict. This would also maintain compatibility with old maps/constructions.

EDIT: Looking at the code, it seems backwards compatibility is not an issue. Adding the aliases `minetest.register_alias("mesecons_insulated:insulated_off", "mesecons_insulated:insulated_grey_off")
minetest.register_alias("mesecons_extrawires:corner_off", "mesecons_extrawires:insulated_corner_grey_off")
minetest.register_alias("mesecons_extrawires:tjunction_off", "mesecons_extrawires:insulated_tjunction_grey_off")` seems to fix the craft conflicts.

**Comment by VanessaE** [comment]
This needs addressed in the [unifiedmesecons mod](https://github.com/cheapie/unifiedmesecons), not here.
