### ISSUE TITLE
Wool coloring conflicts

### ISSUE THREAD

**Issue by lenkaplz** [VanessaE/dreambuilder_modpack#14]
When trying to craft brown wool (from wool and brown dye), the output is orange wool, not brown wool. Similar thing happens when mixing dark green dye with wool - the output is green wool, not dark green wool.

The recipe for orange wool is any wool + any item from group dye excolour_orange which includes brown dye as well.

**Comment by VanessaE** [comment]
This is a minetest_game issue.  No wool crafting recipes exist in dremabuilder.

**Comment by lenkaplz** [comment]
I tried playing minetest_game without any other modpack and couldn't reproduce the issue. After creating a new world with dreambuilder modpack the issue reappeared.

**Comment by lenkaplz** [comment]
Enabling just technic mod pack (with its dependencies) triggers this behavior.
