### ISSUE TITLE
Add Readme.md

### ISSUE THREAD

**Issue by Fixer-007** [VanessaE/dreambuilder_modpack#15]
That includes most of important information from forum.

**Comment by VanessaE** [comment]
af2fedcf9998bb4a854c2cfd63e4cdad91a6dd5d

**Comment by mckaygerhard** [comment]
Excelent README, thanks!

**Comment by VanessaE** [comment]
You're quite welcome.  It was kinda half-assed, but it seems okay to me :smiley:.  Also I've made a new release of Dreambuilder today (it's not git tagged, so just use today's last commit).  Might be a good point to base your Debian package on.

If you catch any errors or find any new bugs, please let me know
