### ISSUE TITLE
How to install this subgame?

### ISSUE THREAD

**Issue by Morovaille** [VanessaE/dreambuilder_modpack#2]
I tried to install this subgame, but the `game.conf` file is missing. How to play dreambuilder?

**Comment by VanessaE** [comment]
As the repo name implies, this is not a subgame (anymore).  It's a modpack, and installs like any other mod or modpack.  Put it in <minetest dir>/mods and enable it for the world you want, as if you were enabling some other mod.

Make sure, at first, that only dreambuilder_modpack is enabled for that world - don't enable any other mods/modpacks.  Later you can enable other mods if you want, most stuff should work fine, but be sure you don't try to add in some mod that Dreambuilder already has, as this might cause a conflict.

**Comment by Boiethios** [comment]
Thank you for explanation! Perhaps you may add it in the README, to permit everybody that download the modpack to install it easily.

**Comment by Morovaille** [comment]
Thank you for explanation! Perhaps you may add it in the README, to permit everybody that download the modpack to install it easily, and know his particularity?
