### ISSUE TITLE
Add `boost carts` mod as better alternative

### ISSUE THREAD

**Issue by Fixer-007** [VanessaE/dreambuilder_modpack#3]
This is reworked and improved version of PilzAdam carts by Krock that at least for me runs fine on remote server I tested, had a good experience with it. Please add it, since dreambuilder is incomplete without carts.

MOD is here: https://forum.minetest.net/viewtopic.php?f=11&t=10172

**Comment by VanessaE** [comment]
f18f36ac0d5416311b74160942e5f4946742c7d1
