### ISSUE TITLE
Inventory top row has some garbage rendering

### ISSUE THREAD

**Issue by Fixer-007** [VanessaE/dreambuilder_modpack#5]
I've encountered this on close to newest dreambuilder on localhost and on some of Vanessa's server, using minetest build as of today. Visible in default creative and survival inventory.
Demo of the bug:
https://i.imgur.com/UBXH47B.png

It also happens on Vanessa Creative-Building server, place a simple chest and check it, you will have the same problem: https://i.imgur.com/lVVlcyE.png

**Comment by VanessaE** [comment]
Not a dreambuilder issue, happens on a non-DB server also.
